---
title: "Logistic Regression Donner Party"
author: "Dr K"
date: "November 19, 2018"
output: html_document
---
 

```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
library (leaps)
```

## import fist CSV using the import function that Luz

# Predicting Fish Weight  

```{r}
Fish = read.csv('Fish.csv')
Perch = filter(Fish, Species == 'Perch')
Perch = subset (Perch, select= -Species)
weightPerch = lm(Weight~Length1+Length2+Length3+Height+Width,data=Perch)
summary.lm(weightPerch)
```




## Perch

### Best Models

### Best Two regressor model
```{r}
regsubsets.out <-
    regsubsets(Weight ~. , data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
```
The Best two variables are height and width.




## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements